### PR TITLE
Added support for `mulitpart/form-data` in AWS API Gateway

### PR DESCRIPTION
**Pull request by jjmachan**
This is supposed to fix https://github.com/bentoml/BentoML/issues/1822

### CODE REVIEW

**Comment by jjmachan** [comment]
hey @NaxAlpha can you try out this fix and let me know if it works

**Comment by NaxAlpha** [comment]
sure let me try this!

**Comment by NaxAlpha** [comment]
unfortunately I am getting this error now:
image

running the docker image **without** `--gpus all` locally gives the same error.

**Comment by jjmachan** [comment]
this could be because of some nvidia-container-runtime but will need some time to figure this out unfortunately. Which instance_type are you using?

**Comment by NaxAlpha** [comment]
For this service: `ml.g4dn.xlarge`

**Comment by NaxAlpha** [comment]
While I could deploy this service last week on GPU, somehow, it is not working right now. Also, I am not sure if it is related to the current issue, but I will try multipart on another service deployed on a CPU instance. And let you know!

**Comment by jjmachan** [comment]
Thanks @NaxAlpha! 

The API Gateway is still not configured properly for the ImageInput handler. Can you try testing it with the FileInput handler too? Really sorry for these inconveniences but will get these ironed out ASAP.

**Comment by NaxAlpha** [comment]
Ok just tested a CPU service. The fix is working perfectly!

**Comment by NaxAlpha** [comment]
BTW CPU service looks something like this:
```
class Model(bentoml.BentoService):
    @bentoml.api(
        input=MultiFileInput(
            input_names=[
                "image1",
                "image2",
                "config",
            ]
        ),
        batch=False,
    )
    def predict(self, image1: FileLike, image2: FileLike, config: FileLike):
        ...
```

**Comment by jjmachan** [comment]
We have figured out a better approach to this problem here #20 hence closing this.

**Pull request closed without merging**
